# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            SRCP AI-Audit
tagline:          ''
description:      'A research into the bias of Large Language Models (LLMs) by the interns of Dr. Mashhadi team of the University of Washington 2024'
url:              "https://c-is-for-chi.github.io/test/"
baseurl:          "/test"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/c-is-for-chi/test
